export const ENV = {
  appId: process.env.VITE_APP_ID ?? "local",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  demoMode: process.env.DEMO_MODE === "1",
  demoOpenId: process.env.DEMO_OPEN_ID ?? "demo",
  demoName: process.env.DEMO_NAME ?? "Demo User",
  authMode: (process.env.AUTH_MODE ?? "local") as "local" | "oauth" | "demo",
  passwordPepper: process.env.AUTH_PASSWORD_PEPPER ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
};
